# Configuration preset layer for LRP temporary Wizard's Den servers.
# Intended to be loaded after wizardsDen.toml

# hostname is a placeholder
# needs region tag

[game]
soft_max_players = 50
hostname = "[JP]田島稲のSS14サーバー[Test]"
desc = "[Vanilla][RP]Space Station 14の日本語サーバー。"
panic_bunker.enabled = false
panic_bunker.disable_with_admins = false
panic_bunker.enable_without_admins = false
panic_bunker.custom_reason = ""

[hub]
tags = "lang:ja,region:unspecified,rp:low"
